#ifndef _TPM2_SIMULATOR_INCLUDE_VENDOR_CODE_STRING_H
#define _TPM2_SIMULATOR_INCLUDE_VENDOR_CODE_STRING_H

char *GetVendorCodeString(uint16_t command_code);

#endif /* _TPM2_SIMULATOR_INCLUDE_VENDOR_CODE_STRING_H */