#!/usr/bin/env bash
out="$1"
user=$(whoami)
hostname=$(cat /etc/hostname)
date=$(date)

cat <<EOF >"$out"
/* This file is automatically generated by image_utils/version.sh.
 * Do not modify unless you know what you are doing!
 */
#define BUILDSTRING "Built by ${user}@${hostname} on ${date}"
EOF